### ISSUE TITLE
这个东西是谁负责的？

### ISSUE THREAD

**Issue by galenyuan** [eleme/sns-sdk#25]
RT，中后台的商户端现在要求内部接入也需要 OAuth，可不可以直接集成到这里？
我可以写前端的逻辑，后端是谁写的呢？

**Comment by rguanghui** [comment]
这个仓库是 public 的，新建一个仓库是做好一点。

**Comment by galenyuan** [comment]
napos 的 oauth 本身也是对外开放的，public 也没所谓的

**Comment by guoyinfeng** [comment]
后端黄老师来写，可以联系下黄老师 @Lellansin @YanagiEiichi

**Comment by Lellansin** [comment]
后端支持有需要可以联系我细聊
